components:
  imageBuilder:
    registryCerts: []
    registry:
      # name must not end with a "/"
      name: gitlab-registry.fc277073030.com
      secretName: image-builder-registry-secret
      path: secrets/registry-auth.json

  workspace:
    pullSecret:
      secretName: image-builder-registry-secret

docker-registry:
  enabled: false
